mutation CreateFirebase {
  user_insert(
    data: {
      username: "Firebase"
      picture: "https://firebase.google.com/static/images/brand-guidelines/logo-vertical.png"
    }
  )
}

mutation CreateUserRonakPuStack {
  # 228627eada1940ae8b48ab916f941210
  user_insert(data: { username: "RonakPustack" })
}

mutation CreateTestPosts {
  post_insertMany(
    data: [
      {
        content: "Hi, this is Ronak99, and here goes my first post."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
      }
      {
        content: "Hi, this is Ronak99, and here goes my second post."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
      }
      {
        content: "Hi, this is Ronak99, and here goes my third post."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
      }
      {
        content: "Hi, this is RonakPustack, and here goes my first post."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
      }
      {
        content: "Hi, this is RonakPustack, and here goes my second post."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
      }
    ]
  )
}

mutation CreateTestComments {
  comment_insertMany(
    data: [
      {
        content: "Ronak99's comment 1."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
        postId: "d6bb2907a46e49f6bfe65f3576eec441"
      }
      {
        content: "Ronak99's comment 2."
        authorId: "a36c6b86bf2c4dab9679fe6d263a399a"
        postId: "d6bb2907a46e49f6bfe65f3576eec441"
      }
      {
        content: "RonakPustack's Comment."
        authorId: "5c4dc65636bd46e780fc7c97efb844ce"
        postId: "d6bb2907a46e49f6bfe65f3576eec441"
      }
    ]
  )
}

query AllPostByOneUser {
  user(id: "a36c6b86bf2c4dab9679fe6d263a399a") {
    id
    username
    posts_on_author(limit: 2) {
      id
      content
    }
  }
}

query MyUser {
  users {
    id
    username
  }
}

query AllCommentsByOneUser {
  user(id: "a36c6b86bf2c4dab9679fe6d263a399a") {
    id
    username
    posts_on_author(limit: 2) {
      content
      comments_on_post {
        id
        author {
          id
          username
        }
        content
      }
    }
  }
}

query GetAllPostsByUser($id: UUID!) @auth(level: USER) {
  user(id: $id) {
    posts: posts_on_author {
      content
      createdAt
      comments_on_post {
        id
        author {
          id
          username
          picture
        }
      }
    }
  }
}
